name: Deploy to Wiki
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.WIKI_ACCESS_TOKEN}}
          fetch-depth: 0
      - name: Add remote
        run: git remote add deployment https://github.com/${{github.repository_owner}}/test-oppia.wiki.git
      - name: Debugging
        run: |
          git fetch deployment
          git diff deployment/master
          git log
      - name: Deploy
        run: |
          git push deployment develop:master
