name: Deploy to Wiki
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Transfer credentials from GitHub secrets to git credential helper
        run: |
          git config credential.helper 'cache --timeout=900'
          echo 'protocol=https\nhost=github.com\nusername=${{secrets.WIKI_ACCESS_USER}}\npassword=${{secrets.WIKI_ACCESS_TOKEN}}\n\n' | git credential store
      - name: Add remote
        run: git remote add deployment https://github.com/${{github.repository_owner}}/test-oppia.wiki.git
      - name: Deploy
        run: git push https://github.com/${{github.repository_owner}}/test-oppia.wiki.git develop:master
